// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main': string;
  'navContainer': string;
  'navbar': string;
  'siteTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
