// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'col-lg': string;
  'col-sm': string;
  'col_lg': string;
  'col_sm': string;
  'footer': string;
  'nav': string;
  'newsletter': string;
}
export const cssExports: CssExports;
export default cssExports;
