// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CardDeck': string;
  'blogCard': string;
  'cardFooter': string;
  'inner': string;
  'linkCard': string;
  'tag': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
